name: test

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.5", "5.4.1", "luajit-2.0.5", "luajit-2.1.0-beta3", "luajit-openresty", "5.1", "5.4"]
        machineTag: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.machineTag }}

    steps:
    - uses: actions/checkout@v2

    - name: Build Lua
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: Transpile gua
      run: |
        lua gua.lua gua.gua gua_.lua
        cmp gua.lua gua_.lua

    - name: Test gua
      run: lua test.lua

